version: 0.2

phases:
  #install:
   # runtime-versions:
      #dotnet: 3.1
    commands:
      - cd Authentication.Solution
      - cd CazhOn.Authentication.Api
      - dotnet restore CazhOn.Authentication.Api.csproj
  build:
    commands:
      -   dotnet build CazhOn.Authentication.Api.csproj
